@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/EIP-PlantUML/main/dist/EIP-PlantUML.puml

skinparam ArrowFontSize 18

<style>
package {
  Padding 100
}
</style>

<<Content>>

@enduml