!$is_consumer_conformist = "<<IS_CONSUMER_CONFORMIST>>"
!$consumer_input_msg_contract = "Consumer"
!if ($is_consumer_conformist == "true")
   !$consumer_input_msg_contract = "Canonical"
!endif
!$consumer_input_msg_type = "File"
!$use_consumer_channel = "true"

package "Consumer" {
    TransactionalConsumer(consumer, "Consumer")
    Message(consumer_input_msg, "\n$consumer_input_msg_type\n($consumer_input_msg_contract)")

    !if ($use_consumer_channel == "true")
         MsgChannel(consumer_channel, "Consumer Channel")
    !endif
    
    !if ($is_consumer_conformist == "true")
      MessageTranslator(consumer_translator,"Translate")
      Message(consumer_translator_output_msg, "\n$consumer_input_msg_type\n(Consumer)")
      !if ($use_consumer_channel == "true")
         consumer_channel -down-> consumer_input_msg 
      !endif
      consumer_input_msg -down-> "<<1>>" consumer_translator
      consumer_translator -down-> "<<2>>" consumer_translator_output_msg
      consumer_translator_output_msg -down-> "<<3>>" consumer
    !else
      !if ($use_consumer_channel == "true")
         consumer_channel -down-> consumer_input_msg 
      !endif
      consumer_input_msg -down-> "<<1>>" consumer
    !endif 
}