@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/EIP-PlantUML/main/dist/EIP-PlantUML.puml

skinparam ArrowFontSize 20

<style>
package {
  Padding 100
}
</style>

<<CONTENT>>

@enduml